name: sibejo_rescue
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  csv: ^6.0.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^10.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/sibejo.png
    - assets/sibejo_horizontal.png

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffffff" # atau warna brand, misalnya #00878A
  adaptive_icon_foreground: "assets/sibejo.png"
  image_path: "assets/sibejo.png"
  remove_alpha_ios: true
