// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO__YguJ5eLsPOhSoqLChOP05ds_RWL9k',
    appId: '1:282787594167:web:a62d455e8f6806473a7232',
    messagingSenderId: '282787594167',
    projectId: 'sibejo-rescue',
    authDomain: 'sibejo-rescue.firebaseapp.com',
    storageBucket: 'sibejo-rescue.firebasestorage.app',
    measurementId: 'G-7SS6WPLVDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSUv3yXgm6aLn_52oRrwlQxRUeUTz3MHA',
    appId: '1:282787594167:android:53a2b04d33b3e41b3a7232',
    messagingSenderId: '282787594167',
    projectId: 'sibejo-rescue',
    storageBucket: 'sibejo-rescue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0L4f_Vt7gkbQgeYCXmdIzEr4DCnpZ62A',
    appId: '1:282787594167:ios:96b983851ece9d3c3a7232',
    messagingSenderId: '282787594167',
    projectId: 'sibejo-rescue',
    storageBucket: 'sibejo-rescue.firebasestorage.app',
    iosBundleId: 'id.sibejo.sibejoRescue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0L4f_Vt7gkbQgeYCXmdIzEr4DCnpZ62A',
    appId: '1:282787594167:ios:96b983851ece9d3c3a7232',
    messagingSenderId: '282787594167',
    projectId: 'sibejo-rescue',
    storageBucket: 'sibejo-rescue.firebasestorage.app',
    iosBundleId: 'id.sibejo.sibejoRescue',
  );
}
